// Backend Student Data
const studentsData = [
    { id: 1, name: "أشرقت احمد", carrots: 30.5, completed: 3, pending: 1, rank: 1 },
    { id: 2, name: "أمينة عطية", carrots: 23, completed: 3, pending: 2, rank: 2 },
    { id: 3, name: "الدانة محمد", carrots: 34, completed: 3, pending: 1, rank: 3 },
    { id: 4, name: "المياسه المهندى", carrots: 18, completed: 3, pending: 2 },
    { id: 5, name: "اميره مها فحصي", carrots: 14, completed: 3, pending: 1 },
    { id: 6, name: "اميمه كريم", carrots: 20, completed: 3, pending: 2 },
    { id: 7, name: "ايناس احمد", carrots: 27, completed: 3, pending: 1 },
    { id: 8, name: "جوري ابراهيم", carrots: 35, completed: 3, pending: 2 },
    { id: 9, name: "حبيبة وليد", carrots: 19, completed: 3, pending: 1 },
    { id: 10, name: "حنين عمر", carrots: 23, completed: 3, pending: 2 },
    { id: 11, name: "خزانه مراد", carrots: 31, completed: 3, pending: 1 },
    { id: 12, name: "دينا عثمان", carrots: 25, completed: 3, pending: 1 },
    { id: 13, name: "رزان قتيبه", carrots: 2, completed: 2, pending: 2 },
    { id: 14, name: "ريم على", carrots: 28, completed: 2, pending: 1 },
    { id: 15, name: "ريماس عبدالرحمن", carrots: 0, completed: 2, pending: 2 },
    { id: 16, name: "زينب رضا", carrots: 15, completed: 2, pending: 1 },
    { id: 17, name: "زينب سلمان", carrots: 23, completed: 2, pending: 1 },
    { id: 18, name: "سارة سارى", carrots: 27, completed: 2, pending: 2 },
    { id: 19, name: "عائشة احمد قاسم", carrots: 17, completed: 2, pending: 1 },
    { id: 20, name: "فرح علي", carrots: 37, completed: 2, pending: 1 },
    { id: 21, name: "لارين ياسر", carrots: 32, completed: 1, pending: 2 },
    { id: 22, name: "لميس محمد", carrots: 18, completed: 1, pending: 1 },
    { id: 23, name: "ماثر هاشم", carrots: 14, completed: 1, pending: 2 },
    { id: 24, name: "مرام رشدى", carrots: 17, completed: 1, pending: 1 },
    { id: 25, name: "مروه عبدالرزاق", carrots: 30, completed: 1, pending: 2 },
    { id: 26, name: "مريم محمد", carrots: 33, completed: 1, pending: 1 },
    { id: 27, name: "مريم معوض", carrots: 38, completed: 1, pending: 1 },
    { id: 28, name: "ناهد عبدالرؤف", carrots: 20, completed: 1, pending: 2 },
    { id: 29, name: "نانسي محمد هادي", carrots: 26, completed: 1, pending: 1 }
];
